language: "en"
early_access: false
reviews:
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!**/.xml"
  path_instructions:
    - path: "**/*.cs"
      instructions: "Review the C# code."
    - path: "tests/**/*"
      instructions: |
        "Assess the unit test code employing the xunit testing framework. Confirm that:
        - The tests adhere to XUnit's established best practices."
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
    base_branches:
      - "main"
chat:
  auto_reply: false