# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run:  dotnet restore ./src/EastSeat.ResourceIdea.sln

    - name: Clean
      run: dotnet clean ./src/EastSeat.ResourceIdea.sln

    - name: Build  
      run: dotnet build ./src/EastSeat.ResourceIdea.sln --no-restore --framework net8.0 -maxcpucount:1

    - name: Run tests
      run: dotnet test ./src/EastSeat.ResourceIdea.sln --no-build --verbosity normal