name: 'TODO'

on:
  push:
    branches:
      - main
jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Create issue from TODO
      uses: alstr/todo-to-issue-action@v4
      with:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IDENTIFIERS: '[{"name": "TODO,FIXME,BUG", "labels": ["todo,fixme,bug"]}]'
